version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Proyecto1:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: WarriorGYM
      POSTGRES_USER: Gym_Admin
      POSTGRES_PASSWORD: Sup3rS3cur3P@ssw0rd!
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
